spring:
  datasource:
    url: jdbc:mysql://localhost:3307/springessentials
    username: root
    password: root
  application:
    name: springessentials
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081