version: "3.1"
services:
#  app:
#    container_name: springessentials
#    image: springessentials:latest
#    ports:
#      - "8081:8080"
#    restart: always
#    depends_on:
#      - mysql
  mysql:
    image: mysql:5
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springessentials